### ISSUE TITLE
✨ Mobile controls

### ISSUE THREAD

**Issue by dinghino** [HackerHouseHQ/hhhq-mvp#23]
Allow users to navigate when using mobile devices

### Sources

Implementation idea comes from [spacesvr](https://github.com/musehq/spacesvr/blob/master/src/layers/Player/controls/NippleMovement.tsx) and uses [react-device-detect](https://www.npmjs.com/package/react-device-detect) and most importantly [nipple.js](https://yoannmoi.net/nipplejs/) for the actual controls.

### TODO

* [ ] add new `control service` to handle nipplejs
* [ ] add new component (mobile only) to display and use the nipple control
* [ ] if mobile do not use mouse/keyboard
* [ ] if desktop do not use nipple
  * ... what about hybrid devices?

Since we're short on time we can either set up an actual control service (function) that handles the nipple and some events for the state machines OR create a barebone nipple react component that dispatches the input values to the state machines that will take it from there.
